# Generated by Django 2.1.7 on 2020-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_dispatcher_app', '0002_auto_20201219_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
