# Generated by Django 2.1.7 on 2020-12-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_dispatcher_app', '0004_site_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
