# Generated by Django 2.1.7 on 2020-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_dispatcher_app', '0005_site_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='usual_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
