# Generated by Django 2.1.7 on 2020-12-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_dispatcher_app', '0007_site_matche_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='F3_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('image_url', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_text', models.CharField(blank=True, max_length=5000, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('relevant', models.BooleanField(blank=True, null=True)),
                ('industrial_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_dispatcher_app.Site')),
            ],
        ),
    ]
